name: Compilação e Teste FolderFlex

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
      - name: Sincronizando Repositório
        uses: actions/checkout@v4

      - name: Configurando Ambiente .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurando as dependencies
        run: dotnet restore FolderFlex.sln

      - name: Compilando Tudo
        run: dotnet build FolderFlex.sln --configuration ${{ matrix.configuration }} --no-restore

      - name: Rodando Testes de unidade
        run: dotnet test FolderFlexTeste/FolderFlexTeste.csproj --configuration ${{ matrix.configuration }} --no-build --verbosity normal

      - name: Publicando FolderFlex
        run: dotnet publish FolderFlex/FolderFlex.csproj --configuration ${{ matrix.configuration }} --output ./output/FolderFlex

      - name: Publicando Updater
        run: dotnet publish Updater/Updater.csproj --configuration ${{ matrix.configuration }} --output ./output/Updater

      - name: Compactando tudo em um zip
        run: |
          powershell Compress-Archive -Path ./output/* -DestinationPath ./output/FolderFlex_Updater.zip

      - name: Upload dos Artefatos
        uses: actions/upload-artifact@v3
        with:
          name: Build Outputs
          path: ./output/FolderFlex_Updater.zip
