name: Deploy FolderFlex

on:
  push:
    branches: ['master']
    paths-ignore:
      - 'README.md'
      - 'social_preview.jpg'
      - 'docs/**'
      - '.github/workflows/dotnet-desktop.yml'
      - 'dotnet-desktop.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
      - name: Sincronizando Repositório
        uses: actions/checkout@v4

      - name: Removendo versões antigas do .NET
        run: |
          Remove-Item -Path "$env:USERPROFILE\.dotnet" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "$env:USERPROFILE\.nuget\packages" -Recurse -Force -ErrorAction SilentlyContinue
        shell: pwsh

          
      - name: Configurando Ambiente .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.200'

      - name: Restaurando Dependências do .NET (Cache)
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ~/.dotnet
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Restaurando as dependências
        run: dotnet restore FolderFlex.sln

      - name: Compilando Tudo
        run: dotnet build FolderFlex.sln --configuration ${{ matrix.configuration }} --no-restore /p:WarningLevel=0

      - name: Publicando FolderFlex
        run: dotnet publish FolderFlex/FolderFlex.csproj --configuration ${{ matrix.configuration }} --output ./output/

      - name: Criando Pasta para os Arquivos
        run: |
          mkdir ./output/FolderFlexFiles

      - name: Movendo Arquivos para a Nova Pasta
        run: |
          Get-ChildItem ./output/ | Where-Object { $_.Name -ne 'FolderFlexFiles' } | Move-Item -Destination ./output/FolderFlexFiles/ -Force

      - name: Compactando a Pasta
        run: |
          powershell Compress-Archive -Path ./output/FolderFlexFiles -DestinationPath ./output/FolderFlex.zip

      - name: Criando Tag da versão
        id: tag_version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}

      - name: Criando Nova Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "FolderFlex v1.0.${{ github.run_number }}"
          draft: false
          prerelease: true

      - name: Anexando arquivos à release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/FolderFlex.zip
          asset_name: FolderFlex.zip
          asset_content_type: application/zip
